image: administratrix/cicd:latest
definitions:
    caches:
        vendor: vendor
    steps:
        - step: &configure
            name: Configure
            caches:
                - node
                - vendor
            artifacts:
                - config.log
                - config.status
            script:
                - sh configure --with-submodule-deinit --with-force
        - step: &test-script
            name: Test (Script)
            caches:
                - node
                - vendor
            artifacts:
                - test-reports/script/**/*
            script:
                - make test-reports/script
        - step: &test-style
            name: Test (Style)
            caches:
                - node
                - vendor
            artifacts:
                - test-reports/style/**/*
            script:
                - make test-reports/style
        - step: &build-debug
            name: Build (Debug)
            caches:
                - node
                - vendor
            artifacts:
                - build/debug/**/*
            script:
                - make build/debug CI=1
        - step: &build-release
            name: Build (Release)
            caches:
                - node
                - vendor
            artifacts:
                - build/release/**/*
            script:
                - make build/release CI=1
        - step: &build-doc
            name: Build (Doc)
            caches:
                - node
                - vendor
            artifacts:
                - build/doc/**/*
            script:
                - make build/doc CI=1
        - step: &dist
            name: Package
            caches:
                - node
                - vendor
            artifacts:
                - dist/**/*
            script:
                - make dist CI=1
pipelines:
    default:
        - step: *configure
        - parallel:
            steps:
                - step: *test-script
                - step: *test-style
                - step: *build-debug
    branches:
        master:
            - step: *configure
            - parallel:
                steps:
                    - step: *test-script
                    - step: *test-style
            - parallel:
                steps:
                    - step: *build-doc
                    - step: *build-release
            - step: *dist
